version: "2"

services:
  goip-sms-server:
    image: bzmn/goip-sms-server
    container_name: goip-sms-server
    restart: always
    network_mode: bridge
    ports:
      - 44444:44444/udp
      - 80
    environment:
      - MYTIMEZONE=Asia/Novosibirsk
      - GOIP_WEB_LOGIN=smsadmin
      - GOIP_WEB_PASSWORD=mysuperCoOlpassXX1
      - MYSQL_MAIN_HOST=172.17.0.1
      - MYSQL_MAIN_PORT=3306
      - MYSQL_MAIN_DB=goipsms
      - MYSQL_MAIN_LOGIN=goipfedclient
      - MYSQL_MAIN_PASSWORD=yoCOmeOnxxZZ999jhjkh
